name: 'build-project'

on:
  push: # Push always triggers after a merge
    branches: 
      - master
      - develop
  pull_request:

# Defines environment variables
env:
  NETCORE_VERSION: '8.0.x' 

jobs:
  build:
    name: 'run-project-build'
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        
      # Setup the .NET 8.0 SDK environment
      - name: 'setup .NET SDK ${{ env.NETCORE_VERSION }}'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
                  
      # Restore NuGet packages to ensure dependencies are available for the build
      - name: 'restore nuget packages'
        working-directory: './src'
        run: dotnet restore
        
      # Build the project in Release configuration
      - name: 'build project'
        working-directory: './src'
        run: dotnet build --configuration Release --no-restore