name: 'Test and Build'

on:
  push:
  pull_request:

# Defines environment variables
env:
  NETCORE_VERSION: '3.1.200'

jobs:
  build:
    name: 'Test and Build'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      #Setup the environment 
      - name: 'Setup .NET Core SDK ${{ env.NETCORE_VERSION }}'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
                  
      # Restore all nuget packages to prevent issues during build
      - name: 'Restore nuget packages'
        working-directory: 'Source'
        run: dotnet restore
        
      # Build the application
      - name: 'Build application'
        working-directory: 'Source'
        run: dotnet build --configuration Release --no-restore
        
      # Run the project unit tests
      - name: 'Run unit tests'
        working-directory: 'Source'
        run: dotnet test --no-build --configuration Release
        
      # Optional for deployment ?
      #- if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/master'}}
      #  name: 'Deploy application'
        
