name: Project Validation

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test application
        uses: actions/checkout@v2
        with: 
          dotnet-version: '3.1.x'
      - run: dotnet test
  build:
    runs-on: ubuntu-latest
    needs: [tests]
    if: github.event_name == 'pull_request'
    steps:
      - name: Build Application
        uses: actions/checkout@v2
        with: 
          dotnet-version: '3.1.x'
      - run: dotnet build --configuration Release
