name: 'test-project'

on:
  push: # Push always triggers after a merge
    branches: 
      - master
      - develop
  pull_request:

# Defines environment variables
env:
  NETCORE_VERSION: '8.0.x'

jobs:
  build:
    name: 'run-unit-tests'
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3 
        
      # Setup the .NET 8.0 SDK environment
      - name: 'setup .NET SDK ${{ env.NETCORE_VERSION }}'
        uses: actions/setup-dotnet@v3 
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
                  
      # Restore all NuGet packages to ensure dependencies are available
      - name: 'restore nuget packages'
        working-directory: './src'
        run: dotnet restore
        
      # Run the project unit tests
      - name: 'run project tests'
        working-directory: './src'
        run: dotnet test --configuration Release